set -g default-terminal "tmux-256color"
set -g status-style fg=white,bg=blue # bottom bar style
set -g mouse on

# change prefix
unbind C-b
set-option -g prefix M-q
bind-key M-q send-prefix

# change h(orizontal) and v(ertical) split keys
bind v split-window -h
bind h split-window -v
unbind '"'
unbind %

# navigate between panes
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# resize panes
bind -n M-Left resize-pane -L
bind -n M-Right resize-pane -R
bind -n M-Up resize-pane -U
bind -n M-Down resize-pane -D
